[versions]
kotlin = "2.2.21"
agp = "8.13.2"
detekt = "1.23.8"
ktlint = "12.1.0"
firebaseAppdistribution = "5.2.0"
grgit = "5.3.3"
publish = "2.0.0"
okhttp = "5.3.2"
retrofit = "3.0.0"
retrofitSerialzation = "1.0.0"
junit = "6.0.1"
ksp = "2.3.4"
play-publish = "v3-rev20231115-2.0.0"
googleAuth = "1.41.0"
kotlinxSerialization = "1.9.0"
pluginCore = "1.0.0"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
firebaseAppdistribution = { module = "com.google.firebase:firebase-appdistribution-gradle", version.ref = "firebaseAppdistribution" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitSerialization = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofitSerialzation" }
grgitCore = { module = "org.ajoberstar.grgit:grgit-core", version.ref = "grgit" }
grgitGradle = { module = "org.ajoberstar.grgit:grgit-gradle", version.ref = "grgit" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junit" }
serializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
# plugin-core is used for CI/CD build in settings.gradle.kts
plugin-core = { group = "ru.kode.android", name = "build-publish-novo-core", version.ref = "pluginCore" }

kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint-plugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ksp-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
play-publish = { module = "com.google.apis:google-api-services-androidpublisher", version.ref = "play-publish" }
google-auth = { module = "com.google.auth:google-auth-library-oauth2-http", version.ref = "googleAuth" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
firebaseAppdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebaseAppdistribution" }
grgit = { id = "org.ajoberstar.grgit", version.ref = "grgit" }
publish = { id = "com.gradle.plugin-publish", version.ref = "publish" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
